### PR TITLE
Upgrade formula to new standards

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by n-rodriguez** [comment]
> Just a quick note for now: we've got the updated matrix running in Cirrus (see [`.cirrus.yml`](https://github.com/saltstack-formulas/syslog-ng-formula/blob/659d13a3a8bfbbb416e83aad372d32e6c09df65d/.cirrus.yml)).

Do we need to keep cirrus on this formula?

**Comment by myii** [comment]
> Do we need to keep cirrus on this formula?

@n-rodriguez It's not absolutely necessary but I was hoping to keep at least some of the repos active on Cirrus, so that we can keep working towards long-term CI solutions (inc. sharing the load with Travis, working out if we can get FreeBSD and Windows working, etc.).  There are only two repos using Cirrus at the moment: `rkhunter` and this one.  All you have to do is move the changes you made in `.travis.yml` to `.cirrus.yml` -- and that's only the matrix.  If you're really not happy, then we can move over to Travis instead.

**Comment by n-rodriguez** [comment]
>  All you have to do is move the changes you made in `.travis.yml` to `.cirrus.yml`

done

>  If you're really not happy, then we can move over to Travis instead.

I'm fine with it :+1:

**Comment by myii** [comment]
@n-rodriguez OK, we should be able to get `amazonlinux-2` working by [enabling the EPEL repo](https://www.syslog-ng.com/community/b/blog/posts/installing-syslog-ng-aws-linux-ami).  I'll add that commit here if it works at my end.

**Comment by myii** [comment]
@n-rodriguez Good news, with the changes I've tested, this is working across all 28 of our instances now (including `arch-base-latest`):

* Everything working but `amazonlinux-2` and `arch-base-latest`:
  - https://cirrus-ci.com/build/5764838296387584 (e)
* Got `amazonlinux-2` working:
  - https://cirrus-ci.com/build/5878059170791424
* Got `arch-base-latest` working:
  - https://cirrus-ci.com/build/5666809962823680

One nice thing about Cirrus is that it runs around 8 instances concurrently, so it can finish pretty fast at good times.

I'm going to clean up the commits and then add them here, for your perusal before merging.

**Comment by myii** [comment]
@n-rodriguez So I've added 3 commits to this PR:

#### 4e46ea0 -- feat(install): provide EPEL repo configuration for `Amazon Linux-2`

* Based on https://github.com/saltstack-formulas/openvpn-formula/pull/122

#### 2112711 -- feat(platform): add support for `Arch`

* Used information from https://wiki.archlinux.org/index.php/Syslog-ng
* Didn't provide any specific version information (e.g. as found in `osfinger.map`); that could be taken from here:
  - https://www.archlinux.org/packages/?name=syslog-ng

#### 373ff11 -- chore: use `semantic-release` cross-formula standard structure

* This commit could be avoided entirely by:
  - Rebasing this PR on the latest `upstream`
  - Removing any changes made to `.travis.yml` (i.e. removing commits 2049866 and 2a94fab)

**Comment by myii** [comment]
@n-rodriguez Right, since the `lint` stage hasn't run during the course of this PR, got some `yamllint` errors to fix.

https://travis-ci.com/saltstack-formulas/syslog-ng-formula/builds/129135816#L210-L217:

```bash
$ yamllint -s .
./test/salt/pillar/syslog_ng.sls
  4:24      warning  truthy value should be one of [false, true]  (truthy)
  6:16      warning  truthy value should be one of [false, true]  (truthy)
  7:17      warning  truthy value should be one of [false, true]  (truthy)
  16:7      error    wrong indentation: expected 8 but found 6  (indentation)
  20:7      error    wrong indentation: expected 8 but found 6  (indentation)
  25:7      error    wrong indentation: expected 8 but found 6  (indentation)
```

I'll just append another commit to fix that.

**Comment by n-rodriguez** [comment]
@myii do you think we can merge it?

**Comment by myii** [comment]
@n-rodriguez Sure, I just wanted you to review the commits I added.  Merged.

**Comment by n-rodriguez** [comment]
> @n-rodriguez Sure, I just wanted you to review the commits I added. Merged.

Thank you!

**Pull request merged**
